### ISSUE TITLE
Provides 34 Saturation

### ISSUE THREAD

**Issue by Sweek9** [bl4ckscor3/CookieBlock#3]
Mod: v1.2.1
MC: v1.20.1
Forge: v47.2.17
Details:
According to [the wiki](https://minecraft.fandom.com/) [a cookie](https://minecraft.fandom.com/wiki/Cookie) has a saturation of 0.4. So x9 would be 3.6. I have a mod which shows saturation as a glow around the hunger meter, and another that displays the hunger and saturation of items in inventory tooltips. The tooltip shows that the cookie block adds 1 leg outline (2 saturation) x17 (= 34), and eating one maximizes my saturation (20). Instantly bringing me to full health without losing any hunger even when I’m near death, which is too cheaty. How fast it is to eat the cookie block feels a bit cheaty too. I think the cookie time x8.2 would be a good balance with the game.

**Comment by bl4ckscor3** [comment]
Thank you for bringing this to my attention. I felt like ~13 seconds is a bit too much, given eating 9 cookies right after each other takes about 14s. I've decided to go with ~10s eating time.

EDIT: There will be a server config to adjust this value.

**Comment by bl4ckscor3** [comment]
This has now been released in v1.3 of the mod.
